<a href="https://colab.research.google.com/github/0701Vatsal/ML_Practicals/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [2]:
print(np.__version__)

1.19.5


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr1 = np.array(15)
print(arr1)

15


In [5]:
arr2 = np.array([[10,20,30,40],[6,7,8,9]])
print(arr2)

[[10 20 30 40]
 [ 6  7  8  9]]


In [6]:
arr3 = np.array([[[10,20,30,40],[6,7,8,9]],[[11,12,13],[14,15,16]]])
print(arr3)

[[list([10, 20, 30, 40]) list([6, 7, 8, 9])]
 [list([11, 12, 13]) list([14, 15, 16])]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [7]:
#checking number of dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
0
2
2


In [8]:
arr4 =np.array([1,2,3,4],ndmin=4)
print(arr4)
print(arr.ndim)

[[[[1 2 3 4]]]]
1


In [9]:
print(arr[3])

40


In [10]:
print(arr2[1])

[6 7 8 9]


In [11]:
print(arr2[1][1])

7


In [12]:
print(arr2[1][2] + arr2[1][2])

16


In [13]:
a = np.array([1,2,3,4,5,6,7,8])
print(a[3:])
print(a[:3])
print(a[:])
print(a[-2:])
print(a[-3:-1])
print(a[2:5])
print(a[1:5:2])

[4 5 6 7 8]
[1 2 3]
[1 2 3 4 5 6 7 8]
[7 8]
[6 7]
[3 4 5]
[2 4]


In [15]:
import pandas as pd
data = np.array([['','Col1','Col2'],
                ['Row1',10,20],
                ['Row2',30,40]])
                
print(pd.DataFrame(data=data[1:,1:],index=data[1:,0],columns=data[0,1:]))

     Col1 Col2
Row1   10   20
Row2   30   40


In [16]:
# creating the Numpy array 
array = np.array([[1, 1, 1], [2, 4, 8], [3, 9, 27],  
                  [4, 16, 64], [5, 25, 125], [6, 36, 216],  
                  [7, 49, 343]]) 
  
# creating a list of index names 
index_values = ['first', 'second', 'third', 
                'fourth', 'fifth', 'sixth', 'seventh'] 
   
# creating a list of column names 
column_values = ['number', 'squares', 'cubes'] 
  
# creating the dataframe 
df = pd.DataFrame(data = array,  
                  index = index_values,  
                  columns = column_values) 
  
# displaying the dataframe 
print(df) 

         number  squares  cubes
first         1        1      1
second        2        4      8
third         3        9     27
fourth        4       16     64
fifth         5       25    125
sixth         6       36    216
seventh       7       49    343
